/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import ControleAluno.txt;
import javax.swing.JOptionPane;



public final class TelaAluno extends javax.swing.JInternalFrame {

    TelaPrincipal b = new TelaPrincipal();

    public TelaAluno() {
        initComponents();
        desabilitarBotoes();
        desabilitarCampos();
        
        ControleAluno.Aluno.TabelaA(tabelaR, txt.listaAluno);

    }

    public void desabilitarBotoes() {
        BtnSair.setEnabled(false);
        BtnSalvar.setEnabled(false);
        BtnCancelar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnVer.setEnabled(false);
    }

    public void habilitarBotoes() {

        BtnSair.setEnabled(true);
        BtnSalvar.setEnabled(true);
        BtnCancelar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnVer.setEnabled(true);

    }

    public void desabilitarCampos() {
        txtCurso.setEnabled(false);
        txtDiscip.setEnabled(false);
        txtNome.setEnabled(false);
        txtProf.setEnabled(false);
        FormatNota1.setEnabled(false);
        FormatNota2.setEnabled(false);
        FormatNota3.setEnabled(false);
        Csala.setEnabled(false);
        Cturma.setEnabled(false);
        txtNum.setEnabled(false);
    }

    public void hablitarCampos() {

        txtCurso.setEnabled(true);
        txtDiscip.setEnabled(true);
        txtNome.setEnabled(true);
        txtProf.setEnabled(true);
        FormatNota1.setEnabled(true);
        FormatNota2.setEnabled(true);
        FormatNota3.setEnabled(true);
        Csala.setEnabled(true);
        Cturma.setEnabled(true);
        txtNum.setEnabled(true);
        txtNome.requestFocus();
    }

    public void limparaCampos() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtProf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FormatNota2 = new javax.swing.JFormattedTextField();
        FormatNota1 = new javax.swing.JFormattedTextField();
        FormatNota3 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaR = new javax.swing.JTable();
        BtnCancelar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        txtNum = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        Csala = new javax.swing.JSpinner();
        Cturma = new javax.swing.JSpinner();
        txtCurso = new javax.swing.JSpinner();
        txtDiscip = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Registro de notas dos alunos");
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 30, 80, 20);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Curso");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 90, 90, 21);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome do Professor");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 150, 330, 21);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Sala");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 270, 100, 21);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Turma");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 270, 100, 21);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Disciplina");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 210, 110, 21);

        txtNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtNome);
        txtNome.setBounds(90, 50, 260, 30);

        txtProf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtProf);
        txtProf.setBounds(90, 170, 260, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Primeira nota");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(400, 80, 130, 21);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Segunda nota");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(400, 190, 130, 20);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Terceira nota");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(400, 130, 130, 20);

        try {
            FormatNota2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(FormatNota2);
        FormatNota2.setBounds(400, 160, 50, 30);

        try {
            FormatNota1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(FormatNota1);
        FormatNota1.setBounds(400, 100, 50, 30);

        try {
            FormatNota3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(FormatNota3);
        FormatNota3.setBounds(400, 220, 50, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/aplicativos_1100_Folder_blue.png"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel12);
        jLabel12.setBounds(680, 30, 230, 300);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo);
        btnNovo.setBounds(150, 350, 130, 40);

        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/tick.png"))); // NOI18N
        BtnSalvar.setText("Salvar");
        BtnSalvar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalvar);
        BtnSalvar.setBounds(310, 350, 110, 40);

        BtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add_1.png"))); // NOI18N
        BtnSair.setText("Sair");
        BtnSair.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(BtnSair);
        BtnSair.setBounds(440, 350, 120, 40);

        tabelaR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelaR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aluno do Alun", "Nome do Prof", "Nº do Aluno", "Turma", "Sala", "Curso", "Disciplina", "Primeira nota", "Segunda nota", "Terceira nota", "Pauta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaR);
        if (tabelaR.getColumnModel().getColumnCount() > 0) {
            tabelaR.getColumnModel().getColumn(0).setResizable(false);
            tabelaR.getColumnModel().getColumn(1).setResizable(false);
            tabelaR.getColumnModel().getColumn(2).setResizable(false);
            tabelaR.getColumnModel().getColumn(3).setResizable(false);
            tabelaR.getColumnModel().getColumn(4).setResizable(false);
            tabelaR.getColumnModel().getColumn(5).setResizable(false);
            tabelaR.getColumnModel().getColumn(6).setResizable(false);
            tabelaR.getColumnModel().getColumn(7).setResizable(false);
            tabelaR.getColumnModel().getColumn(8).setResizable(false);
            tabelaR.getColumnModel().getColumn(9).setResizable(false);
            tabelaR.getColumnModel().getColumn(10).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 410, 990, 240);

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Exit.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(BtnCancelar);
        BtnCancelar.setBounds(580, 350, 130, 40);

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder-horizontal.png"))); // NOI18N
        btnVer.setText("Ver outra lista");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer);
        btnVer.setBounds(730, 350, 150, 40);

        txtNum.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        getContentPane().add(txtNum);
        txtNum.setBounds(320, 300, 70, 26);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Número do Aluno");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 267, 210, 30);

        Csala.setModel(new javax.swing.SpinnerListModel(new String[] {"Sala 1", "Sala 2", "Sala 3", "Sala 4", "Sala 5", "Sala 6", "Sala 7", "Sala 8", "Sala 9", "Sala 10"}));
        getContentPane().add(Csala);
        Csala.setBounds(210, 300, 80, 26);

        Cturma.setModel(new javax.swing.SpinnerListModel(new String[] {"A1", "B2", "C3", "D4", "E5", "F6", "G7", "H8", "I9", "J10"}));
        getContentPane().add(Cturma);
        Cturma.setBounds(90, 300, 70, 26);

        txtCurso.setModel(new javax.swing.SpinnerListModel(new String[] {"CC", "SI", "DES", "EDC", "ETC"}));
        getContentPane().add(txtCurso);
        txtCurso.setBounds(90, 120, 120, 26);

        txtDiscip.setModel(new javax.swing.SpinnerListModel(new String[] {"Programação", "Algébras", "Calculo", "Inglês Técnico", "Física"}));
        getContentPane().add(txtDiscip);
        txtDiscip.setBounds(90, 240, 130, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/3D_HD (195).jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 650);

        setBounds(100, 1, 1023, 668);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        habilitarBotoes();
        hablitarCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza de que quer sair dessa janela ?", "Confirmar", JOptionPane.YES_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            dispose();

        }
    }//GEN-LAST:event_btnVerActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        desabilitarBotoes();
        desabilitarCampos();
        ControleAluno.Aluno.adicionarAluno(txtNome.getText(), txtProf.getText(),
                txtNum.getValue().toString(),
                Cturma.getValue().toString(),
                Csala.getValue().toString(),
                txtCurso.getValue().toString(),
                txtDiscip.getValue().toString(),
                FormatNota1.getText(),
                FormatNota2.getText(),
                FormatNota3.getText());
        ControleAluno.Aluno.TabelaA(tabelaR, txt.listaAluno);

        JOptionPane.showMessageDialog(null, "Dados salvo com sucesso!", "Suceso", 1);

    }//GEN-LAST:event_BtnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnSair;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JSpinner Csala;
    private javax.swing.JSpinner Cturma;
    private javax.swing.JFormattedTextField FormatNota1;
    private javax.swing.JFormattedTextField FormatNota2;
    private javax.swing.JFormattedTextField FormatNota3;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaR;
    private javax.swing.JSpinner txtCurso;
    private javax.swing.JSpinner txtDiscip;
    private javax.swing.JTextField txtNome;
    private javax.swing.JSpinner txtNum;
    private javax.swing.JTextField txtProf;
    // End of variables declaration//GEN-END:variables
}
